name: Kyonet Bot

on:
  workflow_dispatch:

  schedule:
    - cron: '0 23 * * *'
    - cron: '0 11 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Run Bot
        run: node notify.js
        env:
          KYONET_ID: ${{ secrets.KYONET_ID }}
          KYONET_PASS: ${{ secrets.KYONET_PASS }}
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK }}
