name: Kyonet Auto Notify

on:
  schedule:
    - cron: '0 23 * * *'  # 08:00 JST
    - cron: '0 11 * * *'  # 20:00 JST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install puppeteer

      - name: Run bot
        run: node notify.js
        env:
          KYONET_ID: ${{ secrets.KYONET_ID }}
          KYONET_PASS: ${{ secrets.KYONET_PASS }}
          WEBHOOK: ${{ secrets.WEBHOOK }}
